import React, { useCallback, useState } from 'react';
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useFocusEffect } from '@react-navigation/native';
import apiClient from '../services/ApiClient';
import DriverBottomNav from '../components/DriverBottomNav';
import { colors, font, radius, spacing, shadow } from '../theme/theme';

type Period = { amount: string | number; rides: number };
type Month = { month: string; amount: string | number; rides: number };
export default function DriverEarningsScreen() {
  const [months, setMonths] = useState<Month[]>([]); const [thisWeek, setThisWeek] = useState<Period>({ amount: '0', rides: 0 }); const [lastWeek, setLastWeek] = useState<Period>({ amount: '0', rides: 0 }); const [total, setTotal] = useState('0'); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false);
  const load = useCallback(async (refresh = false) => { refresh ? setRefreshing(true) : setLoading(true); try { const response = await apiClient.get('/driver/earnings'); setMonths(response.data?.months || []); setThisWeek(response.data?.thisWeek || { amount: '0', rides: 0 }); setLastWeek(response.data?.lastWeek || { amount: '0', rides: 0 }); setTotal(response.data?.total || '0'); } finally { setLoading(false); setRefreshing(false); } }, []);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  const current = months[0];
  const money = (value: string | number) => typeof value === 'number' ? String(value) : value;
  return <View style={styles.container}><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => load(true)} tintColor={colors.green} />} contentContainerStyle={styles.content}>
    <Text style={styles.title}>Earnings</Text><Text style={styles.subtitle}>Compare your completed ride earnings by month</Text>
    {loading ? <ActivityIndicator color={colors.green} style={styles.loader} /> : <>
      <View style={styles.compare}><View style={[styles.earnCard, styles.primary]}><Text style={styles.cardLabelLight}>THIS WEEK</Text><Text style={styles.primaryValue}>R {money(thisWeek.amount)}</Text><Text style={styles.primaryMeta}>{thisWeek.rides} rides</Text></View><View style={styles.earnCard}><Text style={styles.cardLabel}>LAST WEEK</Text><Text style={styles.value}>R {money(lastWeek.amount)}</Text><Text style={styles.meta}>{lastWeek.rides} rides</Text></View></View>
      <View style={styles.compare}><View style={[styles.earnCard, styles.monthCard]}><Text style={styles.cardLabel}>THIS MONTH</Text><Text style={styles.value}>R {money(current?.amount || '0')}</Text><Text style={styles.meta}>{current?.rides || 0} rides</Text></View><View style={[styles.earnCard, styles.monthCard]}><Text style={styles.cardLabel}>LAST MONTH</Text><Text style={styles.value}>R {money(months[1]?.amount || '0')}</Text><Text style={styles.meta}>{months[1]?.rides || 0} rides</Text></View></View>
      <View style={styles.compare}><View style={styles.earnCard}><Text style={styles.cardLabel}>TOTAL EARNINGS</Text><Text style={styles.value}>R {money(total)}</Text><Text style={styles.meta}>{months.reduce((sum, item) => sum + Number(item.rides || 0), 0)} rides</Text></View></View>
      <Text style={styles.section}>MONTHLY EARNINGS</Text>{months.map((item) => <View style={styles.row} key={item.month}><View><Text style={styles.month}>{new Date(`${item.month}-01`).toLocaleDateString('en-ZA', { month: 'long', year: 'numeric' })}</Text><Text style={styles.meta}>{item.rides} completed rides</Text></View><Text style={styles.amount}>R {money(item.amount)}</Text></View>)}
    </>}
  </ScrollView><DriverBottomNav active="DriverEarnings" /></View>;
}
const styles = StyleSheet.create({ container: { flex: 1, minWidth: 0, minHeight: 0, backgroundColor: colors.gray50 }, content: { padding: spacing.lg, paddingBottom: spacing.xl }, title: { color: colors.gray900, fontFamily: font.extrabold, fontSize: 22, marginTop: spacing.sm }, subtitle: { color: colors.gray600, fontFamily: font.medium, fontSize: 12, marginTop: 4 }, compare: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginTop: spacing.lg }, earnCard: { flexGrow: 1, flexBasis: 140, minWidth: 0, minHeight: 102, backgroundColor: colors.white, borderRadius: radius.lg, padding: spacing.md, ...shadow.sm }, monthCard: { minHeight: 92 }, primary: { backgroundColor: colors.green }, cardLabel: { color: colors.gray700, fontFamily: font.bold, fontSize: 9 }, cardLabelLight: { color: colors.white, fontFamily: font.bold, fontSize: 9 }, primaryValue: { color: colors.white, fontFamily: font.extrabold, fontSize: 25, marginTop: 8 }, primaryMeta: { color: colors.white, fontFamily: font.medium, fontSize: 11, marginTop: 2 }, value: { color: colors.gray900, fontFamily: font.extrabold, fontSize: 22, marginTop: 8 }, meta: { color: colors.gray600, fontFamily: font.medium, fontSize: 11, marginTop: 2 }, section: { color: colors.gray700, fontFamily: font.bold, fontSize: 11, marginTop: spacing.xl, marginBottom: spacing.sm }, row: { backgroundColor: colors.white, padding: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.gray100, flexDirection: 'row', justifyContent: 'space-between' }, month: { color: colors.gray900, fontFamily: font.bold, fontSize: 13 }, amount: { color: colors.greenDark, fontFamily: font.bold, fontSize: 13 }, loader: { marginTop: spacing.xxxl } });
