import React, { useCallback, useState } from 'react';
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useFocusEffect } from '@react-navigation/native';
import apiClient from '../services/ApiClient';
import DriverBottomNav from '../components/DriverBottomNav';
import { colors, font, radius, spacing, shadow } from '../theme/theme';

type Ride = { id: number; pickup?: string; destination?: string; fare?: number; completedAt?: string; riderName?: string };
export default function DriverHistoryScreen() {
  const [rides, setRides] = useState<Ride[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [page, setPage] = useState(0);
  const load = useCallback(async (refresh = false) => { refresh ? setRefreshing(true) : setLoading(true); try { const response = await apiClient.get('/driver/history'); setRides(response.data || []); } finally { setLoading(false); setRefreshing(false); } }, []);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  const pageSize = 7; const pageCount = Math.max(1, Math.ceil(rides.length / pageSize)); const visibleRides = rides.slice(page * pageSize, (page + 1) * pageSize);
  return <View style={styles.container}><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setPage(0); load(true); }} tintColor={colors.green} />} contentContainerStyle={styles.content}><Text style={styles.back}>‹ Back</Text><Text style={styles.title}>Ride History</Text><Text style={styles.subtitle}>{rides.length} completed rides</Text>{loading ? <ActivityIndicator color={colors.green} style={styles.loader} /> : rides.length === 0 ? <Text style={styles.empty}>No completed rides yet.</Text> : visibleRides.map((ride) => <View style={styles.card} key={ride.id}><View style={styles.top}><View><Text style={styles.route}>{ride.pickup || 'Pickup'} → {ride.destination || 'Destination'}</Text><Text style={styles.rider}>{ride.riderName || 'Rider'}</Text></View><Text style={styles.amount}>R {String(ride.fare ?? '0')}</Text></View><Text style={styles.date}>{ride.completedAt ? new Date(ride.completedAt).toLocaleDateString('en-ZA', { day: 'numeric', month: 'short', year: 'numeric' }) : 'Completed'}</Text></View>)}</ScrollView><View style={styles.pagination}><TouchableOpacity disabled={page === 0} onPress={() => setPage((value) => Math.max(0, value - 1))} style={[styles.pageButton, page === 0 && styles.disabled]}><Text style={styles.pageText}>‹ Back</Text></TouchableOpacity><Text style={styles.pageLabel}>Page {page + 1} of {pageCount}</Text><TouchableOpacity disabled={page >= pageCount - 1} onPress={() => setPage((value) => Math.min(pageCount - 1, value + 1))} style={[styles.pageButton, page >= pageCount - 1 && styles.disabled]}><Text style={styles.pageText}>Next ›</Text></TouchableOpacity></View><DriverBottomNav active="DriverHistory" /></View>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: colors.gray50 }, content: { padding: spacing.lg, paddingBottom: spacing.md }, back: { color: colors.green, fontFamily: font.semibold, fontSize: 13 }, title: { color: colors.gray900, fontFamily: font.extrabold, fontSize: 22, marginTop: spacing.sm }, subtitle: { color: colors.gray600, fontFamily: font.semibold, fontSize: 12, marginTop: 4 }, card: { backgroundColor: colors.white, borderRadius: radius.lg, padding: spacing.md, marginTop: spacing.sm, ...shadow.sm }, top: { flexDirection: 'row', justifyContent: 'space-between', gap: spacing.sm }, route: { color: colors.gray900, fontFamily: font.bold, fontSize: 13 }, rider: { color: colors.gray600, fontFamily: font.medium, fontSize: 11, marginTop: 5 }, amount: { color: colors.greenDark, fontFamily: font.bold, fontSize: 13 }, date: { color: colors.gray500, fontFamily: font.medium, fontSize: 10, marginTop: 10 }, empty: { color: colors.gray600, fontFamily: font.medium, textAlign: 'center', marginTop: spacing.xxxl }, loader: { marginTop: spacing.xxxl }, pagination: { height: 56, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: spacing.lg, borderTopWidth: 1, borderTopColor: colors.gray200, backgroundColor: colors.white }, pageButton: { paddingHorizontal: spacing.md, paddingVertical: spacing.sm, borderRadius: radius.md, backgroundColor: colors.gray100 }, disabled: { opacity: 0.45 }, pageText: { color: colors.gray800, fontFamily: font.semibold, fontSize: 12 }, pageLabel: { color: colors.gray700, fontFamily: font.semibold, fontSize: 12 } });
