import React, { useCallback, useState } from 'react';
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useFocusEffect, useNavigation } from '@react-navigation/native';
import type { StackNavigationProp } from '@react-navigation/stack';
import { LogOut } from 'lucide-react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import apiClient from '../services/ApiClient';
import DriverBottomNav from '../components/DriverBottomNav';
import { colors, font, radius, spacing, shadow } from '../theme/theme';

type Profile = { fullName?: string; email?: string; phone?: string; rating?: number; totalTrips?: number; approvalStatus?: string; licencePlate?: string; vehicleMake?: string; vehicleYear?: number; faceVerified?: boolean };
type RootStackParamList = { Login: undefined };
export default function DriverProfileScreen() {
  const navigation = useNavigation<StackNavigationProp<RootStackParamList>>();
  const [profile, setProfile] = useState<Profile>({}); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false);
  const load = useCallback(async (refresh = false) => { refresh ? setRefreshing(true) : setLoading(true); try { const response = await apiClient.get('/driver/profile'); setProfile(response.data || {}); } finally { setLoading(false); setRefreshing(false); } }, []);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  const initials = (profile.fullName || 'Driver').split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase();
  const logout = async () => { await AsyncStorage.multiRemove(['authToken', 'user']); navigation.replace('Login'); };
  return <View style={styles.container}><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => load(true)} tintColor={colors.green} />} contentContainerStyle={styles.content}><Text style={styles.back}>‹ Back</Text><Text style={styles.title}>Driver Profile</Text>{loading ? <ActivityIndicator color={colors.green} style={styles.loader} /> : <><View style={styles.identity}><View style={styles.avatar}><Text style={styles.initials}>{initials}</Text></View><View><Text style={styles.name}>{profile.fullName || 'Driver'}</Text><Text style={styles.sub}>{profile.email || 'No email recorded'}</Text><Text style={styles.rating}>★ {Number(profile.rating || 0).toFixed(1)} · {profile.totalTrips || 0} trips</Text></View></View><Text style={styles.section}>VEHICLE</Text><View style={styles.grid}><Info label="MODEL" value={profile.vehicleMake || 'Not recorded'} /><Info label="COLOUR" value="Not recorded" /><Info label="PLATE" value={profile.licencePlate || 'Not recorded'} /><Info label="YEAR" value={profile.vehicleYear ? String(profile.vehicleYear) : 'Not recorded'} /></View><Text style={styles.section}>VERIFICATION STATUS</Text><Status label="Driver approval" value={profile.approvalStatus || 'PENDING'} /><Status label="Face recognition" value={profile.faceVerified ? 'Verified' : 'Pending'} /><Status label="Account email" value={profile.email ? 'Recorded' : 'Missing'} /><TouchableOpacity style={styles.logout} onPress={logout}><LogOut size={18} color={colors.red} /><Text style={styles.logoutText}>Logout</Text></TouchableOpacity></>}</ScrollView><DriverBottomNav active="DriverProfile" /></View>;
}
function Info({ label, value }: { label: string; value: string }) { return <View style={styles.info}><Text style={styles.label}>{label}</Text><Text style={styles.infoValue}>{value}</Text></View>; }
function Status({ label, value }: { label: string; value: string }) { const good = /APPROVED|VERIFIED|RECORDED/i.test(value); return <View style={styles.status}><View style={[styles.check, good && styles.good]}><Text style={styles.checkText}>{good ? '✓' : '!'}</Text></View><View><Text style={styles.statusLabel}>{label}</Text><Text style={[styles.statusValue, good && styles.goodText]}>{value}</Text></View></View>; }
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: colors.gray50 }, content: { padding: spacing.lg, paddingBottom: spacing.xl }, back: { color: colors.green, fontFamily: font.bold, fontSize: 13 }, title: { color: colors.gray900, fontFamily: font.extrabold, fontSize: 22, marginTop: spacing.sm }, identity: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, backgroundColor: colors.white, borderRadius: radius.lg, padding: spacing.md, marginTop: spacing.lg, ...shadow.sm }, avatar: { width: 48, height: 48, borderRadius: 24, backgroundColor: colors.blue, alignItems: 'center', justifyContent: 'center' }, initials: { color: colors.white, fontFamily: font.bold, fontSize: 16 }, name: { color: colors.gray900, fontFamily: font.extrabold, fontSize: 16 }, sub: { color: colors.gray700, fontFamily: font.medium, fontSize: 11, marginTop: 3 }, rating: { color: colors.orange, fontFamily: font.bold, fontSize: 11, marginTop: 4 }, section: { color: colors.gray700, fontFamily: font.extrabold, fontSize: 10, marginTop: spacing.xl, marginBottom: spacing.sm }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, info: { width: '48%', backgroundColor: colors.white, borderRadius: radius.md, padding: spacing.md, ...shadow.sm }, label: { color: colors.gray600, fontFamily: font.bold, fontSize: 9 }, infoValue: { color: colors.gray900, fontFamily: font.bold, fontSize: 12, marginTop: 5 }, status: { backgroundColor: colors.white, borderRadius: radius.md, padding: spacing.md, marginBottom: spacing.sm, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, ...shadow.sm }, check: { width: 21, height: 21, borderRadius: 11, backgroundColor: colors.orange, alignItems: 'center', justifyContent: 'center' }, good: { backgroundColor: colors.green }, checkText: { color: colors.white, fontFamily: font.bold, fontSize: 12 }, statusLabel: { color: colors.gray900, fontFamily: font.bold, fontSize: 12 }, statusValue: { color: colors.orange, fontFamily: font.bold, fontSize: 10, marginTop: 2 }, goodText: { color: colors.greenDark }, logout: { backgroundColor: colors.white, borderRadius: radius.md, padding: spacing.md, marginTop: spacing.sm, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.sm, borderWidth: 1, borderColor: colors.redLight }, logoutText: { color: colors.red, fontFamily: font.extrabold, fontSize: 13 }, loader: { marginTop: spacing.xxxl } });
