import React from 'react';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Banknote, ChevronLeft, CheckCircle2 } from 'lucide-react-native';
import { useNavigation } from '@react-navigation/native';
import { colors, font, radius, spacing, shadow } from '../theme/theme';

export default function PaymentMethodsScreen() {
	const navigation = useNavigation();
	return <View style={styles.container}><ScrollView contentContainerStyle={styles.content}><TouchableOpacity onPress={() => navigation.goBack()} style={styles.back}><ChevronLeft size={18} color={colors.greenDark} /><Text style={styles.backText}>Back</Text></TouchableOpacity><Text style={styles.title}>Payment Methods</Text><Text style={styles.subtitle}>Choose how you pay for your rides</Text><Text style={styles.section}>AVAILABLE PAYMENT</Text><View style={styles.cashCard}><View style={styles.cashIcon}><Banknote size={25} color={colors.white} /></View><View style={styles.cashCopy}><Text style={styles.cashTitle}>Cash</Text><Text style={styles.cashSubtitle}>Pay your driver directly</Text></View><CheckCircle2 size={22} color={colors.white} /></View><View style={styles.note}><Text style={styles.noteTitle}>Cash is selected</Text><Text style={styles.noteText}>Your next ride will use cash unless you choose another method during booking.</Text></View></ScrollView></View>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: colors.gray50 }, content: { padding: spacing.lg }, back: { flexDirection: 'row', alignItems: 'center', gap: 2 }, backText: { color: colors.greenDark, fontFamily: font.bold, fontSize: 13 }, title: { color: colors.gray900, fontFamily: font.extrabold, fontSize: 22, marginTop: spacing.lg }, subtitle: { color: colors.gray600, fontFamily: font.medium, fontSize: 12, marginTop: 4 }, section: { color: colors.gray600, fontFamily: font.bold, fontSize: 10, marginTop: spacing.xl, marginBottom: spacing.sm }, cashCard: { backgroundColor: colors.green, borderRadius: radius.lg, padding: spacing.md, flexDirection: 'row', alignItems: 'center', gap: spacing.md, ...shadow.md }, cashIcon: { width: 44, height: 44, borderRadius: radius.md, backgroundColor: 'rgba(255,255,255,.22)', alignItems: 'center', justifyContent: 'center' }, cashCopy: { flex: 1 }, cashTitle: { color: colors.white, fontFamily: font.extrabold, fontSize: 16 }, cashSubtitle: { color: colors.white, fontFamily: font.medium, fontSize: 11, marginTop: 3 }, note: { backgroundColor: colors.white, borderRadius: radius.md, padding: spacing.md, marginTop: spacing.md, ...shadow.sm }, noteTitle: { color: colors.gray900, fontFamily: font.bold, fontSize: 13 }, noteText: { color: colors.gray600, fontFamily: font.medium, fontSize: 11, marginTop: 5, lineHeight: 17 } });
