import React, { useCallback, useState } from 'react';
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useFocusEffect, useNavigation } from '@react-navigation/native';
import type { StackNavigationProp } from '@react-navigation/stack';
import { AudioLines, MapPin, Send, Siren } from 'lucide-react-native';
import apiClient from '../services/ApiClient';
import { useToast } from '../components/Toast';
import { colors, font, radius, spacing, shadow } from '../theme/theme';
import { SecurityNav } from './SecurityCentreDashboardScreen';

type RootStackParamList = { SecurityDashboard: undefined; ActiveRidesMonitor: undefined; SosAlerts: undefined; ResolvedSos: undefined; AudioRecordings: { incidentId: number; security?: boolean } };
type Alert = { id: number; reference: string; riderName?: string; driverName?: string; gpsLat?: number; gpsLng?: number; rideReference: string; createdAt: string; hasAudio?: boolean };

export default function SosAlertsScreen() {
  const navigation = useNavigation<StackNavigationProp<RootStackParamList>>(); const { showToast } = useToast(); const [active, setActive] = useState<Alert[]>([]); const [resolved, setResolved] = useState<Alert[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [dispatching, setDispatching] = useState<number | null>(null); const [error, setError] = useState('');
  const load = useCallback(async (refresh = false) => { refresh ? setRefreshing(true) : setLoading(true); try { const response = await apiClient.get('/security/sos'); setActive(response.data?.active || []); setResolved(response.data?.resolved || []); setError(''); } catch (err: any) { setError(err?.response?.data?.error || 'Could not load SOS alerts'); } finally { setLoading(false); setRefreshing(false); } }, []);
  useFocusEffect(useCallback(() => { load(); const timer = setInterval(() => load(true), 5000); return () => clearInterval(timer); }, [load]));
  const dispatch = async (id: number) => { setDispatching(id); try { const response = await apiClient.post(`/security/sos/${id}/dispatch`); showToast(response.data?.message || 'Dispatch unit sent to location', 'red'); await load(true); } catch (err: any) { showToast(err?.response?.data?.error || 'Could not dispatch unit', 'red'); } finally { setDispatching(null); } };
  const formatDate = (value: string) => new Date(value).toLocaleString('en-ZA', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' });
  return <View style={styles.container}><View style={styles.fixedContent}><Text style={styles.title}>SOS Alerts</Text>{error ? <View style={styles.error}><Text style={styles.errorText}>{error}</Text><TouchableOpacity onPress={() => load()}><Text style={styles.retryText}>Retry</Text></TouchableOpacity></View> : null}<Text style={styles.activeHeading}>ACTIVE SOS · {active.length}</Text>{loading ? <ActivityIndicator size="large" color={colors.green} /> : active.map((alert) => <View style={styles.activeCard} key={alert.id}><View style={styles.row}><Text style={styles.reference}>{alert.reference}</Text><Text style={styles.timestamp}>{formatDate(alert.createdAt)}</Text></View><Text style={styles.label}>RIDER</Text><Text style={styles.value}>{alert.riderName || 'Unknown rider'}</Text><Text style={styles.label}>DRIVER</Text><Text style={styles.value}>{alert.driverName || 'Unassigned driver'}</Text><View style={styles.location}><MapPin size={15} color={colors.red} /><Text style={styles.locationText}>{alert.gpsLat ?? '-'}, {alert.gpsLng ?? '-'}</Text></View><View style={styles.actions}><TouchableOpacity style={styles.dispatch} onPress={() => dispatch(alert.id)} disabled={dispatching === alert.id}><Send size={16} color={colors.white} /><Text style={styles.actionText}>{dispatching === alert.id ? 'Dispatching...' : 'Dispatch'}</Text></TouchableOpacity><TouchableOpacity style={styles.audio} onPress={() => alert.hasAudio ? navigation.navigate('AudioRecordings', { incidentId: alert.id, security: true }) : showToast('Audio is not available yet. Finish the SOS recording and refresh the list.', 'yellow')}><AudioLines size={16} color={colors.white} /><Text style={styles.actionText}>Audio</Text></TouchableOpacity></View></View>)}</View><ScrollView style={styles.resolvedScroll} showsVerticalScrollIndicator={false} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => load(true)} tintColor={colors.green} />} contentContainerStyle={styles.resolvedContent}><Text style={styles.resolvedHeading}>RESOLVED SOS</Text>{resolved.slice(0, 6).map((alert) => <View style={styles.resolvedCard} key={alert.id}><View><Text style={styles.reference}>{alert.reference}</Text><Text style={styles.resolvedText}>{alert.riderName || 'Unknown rider'} · {formatDate(alert.createdAt)}</Text></View><Text style={styles.resolvedBadge}>RESOLVED</Text></View>)}<TouchableOpacity style={styles.viewAllButton} onPress={() => navigation.navigate('ResolvedSos')}><Text style={styles.viewAllText}>View All SOS</Text><Siren size={15} color={colors.blue} /></TouchableOpacity></ScrollView><SecurityNav active="alerts" onDashboard={() => navigation.navigate('SecurityDashboard')} onRides={() => navigation.navigate('ActiveRidesMonitor')} onAlerts={() => navigation.navigate('SosAlerts')} /></View>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: colors.gray50 }, fixedContent: { padding: spacing.lg, paddingBottom: 0 }, resolvedScroll: { flex: 1, marginHorizontal: spacing.lg }, resolvedContent: { paddingBottom: 92 }, title: { color: colors.gray900, fontFamily: font.extrabold, fontSize: 22, marginBottom: spacing.lg }, error: { backgroundColor: colors.redLight, borderRadius: radius.md, padding: spacing.md, marginBottom: spacing.md }, errorText: { color: colors.red, fontFamily: font.medium, fontSize: 12 }, retryText: { color: colors.blue, fontFamily: font.bold, fontSize: 12, marginTop: spacing.xs }, activeHeading: { color: colors.red, fontFamily: font.bold, fontSize: 11, marginBottom: spacing.sm }, activeCard: { backgroundColor: colors.white, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.red, padding: spacing.md, marginBottom: spacing.lg, ...shadow.sm }, row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, reference: { color: colors.gray900, fontFamily: font.extrabold, fontSize: 15 }, timestamp: { color: colors.gray400, fontFamily: font.regular, fontSize: 11 }, label: { color: colors.gray500, fontFamily: font.bold, fontSize: 9, marginTop: spacing.md }, value: { color: colors.gray900, fontFamily: font.bold, fontSize: 14 }, location: { flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: spacing.md }, locationText: { color: colors.gray700, fontFamily: font.mono, fontSize: 12 }, actions: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.lg }, dispatch: { flex: 1, minHeight: 38, backgroundColor: colors.red, borderRadius: radius.full, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 5 }, audio: { flex: 1, minHeight: 38, backgroundColor: colors.blue, borderRadius: radius.full, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 5 }, actionText: { color: colors.white, fontFamily: font.bold, fontSize: 12 }, resolvedHeading: { color: colors.gray500, fontFamily: font.bold, fontSize: 11, marginBottom: spacing.sm }, resolvedCard: { backgroundColor: colors.white, padding: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.gray200, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, resolvedText: { color: colors.gray500, fontFamily: font.regular, fontSize: 11, marginTop: 3 }, resolvedBadge: { color: colors.greenDark, backgroundColor: colors.greenLight, borderRadius: radius.full, paddingHorizontal: 8, paddingVertical: 4, fontFamily: font.bold, fontSize: 9 }, viewAllButton: { minHeight: 42, marginTop: spacing.md, borderRadius: radius.full, borderWidth: 1, borderColor: colors.blue, backgroundColor: colors.white, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.xs }, viewAllText: { color: colors.blue, fontFamily: font.bold, fontSize: 12 } });